-- Executar após database/schema.sql em PostgreSQL.
-- Permite que a API crie usuários sem informar o identificador manualmente.
ALTER TABLE users
  ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
