-- Executar após 001_enable_user_identity.sql.
-- Perfis iniciais usados pela autorização da API.
ALTER TABLE roles
  ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

INSERT INTO roles (name, description) VALUES
  ('ADMIN', 'Acesso completo e gestão de usuários'),
  ('VENDAS', 'Operações comerciais e vendas'),
  ('ESTOQUE', 'Produtos e movimentações de estoque'),
  ('FINANCEIRO', 'Contas a pagar, receber e financeiro')
ON CONFLICT (name) DO NOTHING;
