-- Executar após 002_seed_roles.sql.
-- Habilita a geração automática dos identificadores usados nos cadastros iniciais.
ALTER TABLE customers
  ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE suppliers
  ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
