-- Executar após 003_enable_party_identity.sql.
-- Habilita a criação de produtos e movimentos de estoque pela API.
ALTER TABLE products
  ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE stock_movements
  ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
