-- Executar após 004_enable_product_inventory_identity.sql.
-- Dados adicionais para compras manuais, importação de NF-e e revisão de preços.
ALTER TABLE purchases
  ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE purchase_items
  ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE purchase_items
  ALTER COLUMN product_id DROP NOT NULL;

ALTER TABLE products
  ADD COLUMN profit_margin_pct DECIMAL(7,2) NOT NULL DEFAULT 0;

ALTER TABLE purchases
  ADD COLUMN source VARCHAR(15) NOT NULL DEFAULT 'MANUAL',
  ADD COLUMN xml_access_key VARCHAR(60),
  ADD COLUMN xml_raw TEXT;

ALTER TABLE purchase_items
  ADD COLUMN xml_item_number INTEGER,
  ADD COLUMN source_code VARCHAR(60),
  ADD COLUMN source_description VARCHAR(255),
  ADD COLUMN cost_before DECIMAL(15,2),
  ADD COLUMN sale_price_before DECIMAL(15,2),
  ADD COLUMN suggested_sale_price DECIMAL(15,2),
  ADD COLUMN resolution_status VARCHAR(20) NOT NULL DEFAULT 'RESOLVED';

CREATE UNIQUE INDEX idx_purchases_xml_access_key
  ON purchases(xml_access_key)
  WHERE xml_access_key IS NOT NULL;
