-- Executar após 005_add_purchase_import_support.sql.
-- Vendas, pagamentos e caixas independentes por vendedor/turno/terminal.
ALTER TABLE sales
  ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE sale_items
  ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE sales
  ADD COLUMN seller_id BIGINT REFERENCES users(id),
  ADD COLUMN cash_session_id BIGINT,
  ADD COLUMN cancelled_at TIMESTAMP;

CREATE TABLE cash_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  terminal_id VARCHAR(100) NOT NULL,
  seller_id BIGINT NOT NULL REFERENCES users(id),
  status VARCHAR(20) NOT NULL DEFAULT 'OPEN',
  opening_amount DECIMAL(15,2) NOT NULL DEFAULT 0,
  opened_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  closed_at TIMESTAMP,
  closing_amount DECIMAL(15,2),
  report_snapshot JSONB,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE sales
  ADD CONSTRAINT fk_sales_cash_session
  FOREIGN KEY (cash_session_id) REFERENCES cash_sessions(id);

CREATE TABLE sale_payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sale_id BIGINT NOT NULL REFERENCES sales(id),
  payment_method VARCHAR(30) NOT NULL,
  amount DECIMAL(15,2) NOT NULL,
  due_date DATE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE cash_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cash_session_id BIGINT NOT NULL REFERENCES cash_sessions(id),
  sale_id BIGINT REFERENCES sales(id),
  type VARCHAR(30) NOT NULL,
  payment_method VARCHAR(30),
  amount DECIMAL(15,2) NOT NULL,
  description VARCHAR(255),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_cash_sessions_terminal_opened ON cash_sessions(terminal_id, opened_at);
CREATE INDEX idx_cash_sessions_seller ON cash_sessions(seller_id, opened_at);
CREATE INDEX idx_cash_events_session ON cash_events(cash_session_id, created_at);
CREATE INDEX idx_sale_payments_sale ON sale_payments(sale_id);
