-- Executar após 006_add_sales_and_cash_sessions.sql.
-- Contas a pagar/receber, origem e baixas parciais.
ALTER TABLE financial_entries
  ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE financial_entries
  ADD COLUMN source VARCHAR(15) NOT NULL DEFAULT 'MANUAL',
  ADD COLUMN document_number VARCHAR(100),
  ADD COLUMN xml_raw TEXT,
  ADD COLUMN sale_id BIGINT REFERENCES sales(id),
  ADD COLUMN purchase_id BIGINT REFERENCES purchases(id),
  ADD COLUMN settled_amount DECIMAL(15,2) NOT NULL DEFAULT 0;

CREATE TABLE financial_settlements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  financial_entry_id BIGINT NOT NULL REFERENCES financial_entries(id),
  cash_session_id BIGINT REFERENCES cash_sessions(id),
  payment_method VARCHAR(30) NOT NULL,
  amount DECIMAL(15,2) NOT NULL,
  settled_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  notes VARCHAR(255)
);

CREATE INDEX idx_financial_entries_type_status_due
  ON financial_entries(type, status, due_date);

CREATE INDEX idx_financial_settlements_entry
  ON financial_settlements(financial_entry_id, settled_at);
