-- Autorizações especiais do PDV, sempre vinculadas ao supervisor que autorizou.
ALTER TABLE sale_items
  ADD COLUMN cancelled_at TIMESTAMP,
  ADD COLUMN cancelled_by BIGINT REFERENCES users(id);

CREATE TABLE pdv_authorizations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  action VARCHAR(30) NOT NULL,
  sale_id BIGINT NOT NULL REFERENCES sales(id),
  sale_item_id BIGINT REFERENCES sale_items(id),
  requested_by BIGINT REFERENCES users(id),
  authorized_by BIGINT NOT NULL REFERENCES users(id),
  amount DECIMAL(15,2),
  reason VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_pdv_authorizations_sale ON pdv_authorizations(sale_id, created_at);
CREATE INDEX idx_pdv_authorizations_authorizer ON pdv_authorizations(authorized_by, created_at);
