-- Devoluções/trocas do PDV: tabela necessária para registrar a devolução
-- e vincular o crédito gerado ao cliente e à venda original.
CREATE TABLE IF NOT EXISTS sales_returns (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sale_id BIGINT NOT NULL REFERENCES sales(id),
  customer_id BIGINT NOT NULL REFERENCES customers(id),
  product_id BIGINT NOT NULL REFERENCES products(id),
  quantity DECIMAL(15,3) NOT NULL CHECK (quantity > 0),
  amount DECIMAL(15,2) NOT NULL CHECK (amount >= 0),
  reason VARCHAR(30) NOT NULL,
  notes VARCHAR(500),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_sales_returns_sale ON sales_returns(sale_id, created_at);
CREATE INDEX IF NOT EXISTS idx_sales_returns_customer ON sales_returns(customer_id, created_at);
CREATE INDEX IF NOT EXISTS idx_sales_returns_product ON sales_returns(product_id, created_at);
