-- Customer store-credit ledger used by returns and PDV credit consumption.
CREATE TABLE IF NOT EXISTS customer_credit_ledger (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL REFERENCES customers(id),
    type VARCHAR(30) NOT NULL CHECK (type IN ('RETURN_CREDIT', 'CREDIT_USE', 'CREDIT_REVERSAL')),
    amount DECIMAL(15,2) NOT NULL CHECK (amount > 0),
    source_return_id BIGINT REFERENCES sales_returns(id),
    sale_id BIGINT REFERENCES sales(id),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_customer_credit_ledger_customer
    ON customer_credit_ledger(customer_id);
CREATE INDEX IF NOT EXISTS idx_customer_credit_ledger_return
    ON customer_credit_ledger(source_return_id);
CREATE INDEX IF NOT EXISTS idx_customer_credit_ledger_sale
    ON customer_credit_ledger(sale_id);
