-- Parcelas financeiras vinculadas a contas a pagar/receber.
-- Mantém o detalhamento das obrigações sem substituir financial_entries.
CREATE TABLE IF NOT EXISTS financial_installments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  financial_entry_id BIGINT NOT NULL REFERENCES financial_entries(id) ON DELETE CASCADE,
  installment_number INTEGER NOT NULL,
  due_date DATE NOT NULL,
  amount DECIMAL(15,2) NOT NULL,
  settled_amount DECIMAL(15,2) NOT NULL DEFAULT 0,
  status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_financial_installment_number UNIQUE (financial_entry_id, installment_number),
  CONSTRAINT ck_financial_installment_amount CHECK (amount >= 0),
  CONSTRAINT ck_financial_installment_settled CHECK (settled_amount >= 0)
);

CREATE INDEX IF NOT EXISTS idx_financial_installments_entry
  ON financial_installments(financial_entry_id);

CREATE INDEX IF NOT EXISTS idx_financial_installments_due_status
  ON financial_installments(due_date, status);
