-- Documento fiscal desacoplado da operação comercial.
-- A venda permanece contabilizada mesmo quando a NFC-e é rejeitada.
CREATE TABLE IF NOT EXISTS sale_fiscal_documents (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sale_id BIGINT NOT NULL UNIQUE REFERENCES sales(id) ON DELETE CASCADE,
  document_type VARCHAR(15) NOT NULL DEFAULT 'GERENCIAL',
  status VARCHAR(20) NOT NULL DEFAULT 'NOT_APPLICABLE',
  attempts INTEGER NOT NULL DEFAULT 0,
  error_code VARCHAR(100),
  error_message VARCHAR(1000),
  access_key VARCHAR(44),
  protocol VARCHAR(100),
  xml_raw TEXT,
  last_attempt_at TIMESTAMP,
  authorized_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ck_sale_fiscal_document_type CHECK (document_type IN ('FISCAL','GERENCIAL')),
  CONSTRAINT ck_sale_fiscal_document_status CHECK (status IN ('NOT_APPLICABLE','PENDING','PROCESSING','AUTHORIZED','REJECTED','CANCELLED')),
  CONSTRAINT ck_sale_fiscal_document_attempts CHECK (attempts >= 0)
);

CREATE INDEX IF NOT EXISTS idx_sale_fiscal_documents_status
  ON sale_fiscal_documents(document_type, status, created_at);
